### ISSUE TITLE
Nyan Cat having rainbows not in his back.

### ISSUE THREAD

**Issue by TemTemmie** [Leurak/MEMZ#27] opened 2017-04-21 21:38 UTC

**Comment by Leurak** [comment] 2017-04-29 08:02
?

**Comment by TemTemmie** [comment] 2017-05-01 15:43
I got a glitch at the Nyan Cat payload when the rainbows aren't in the correct position.

**Comment by Leurak** [comment] 2017-05-01 18:27
I guess this could be a duplicate of #26?

**Comment by TemTemmie** [comment] 2017-05-12 18:03
no

**Closed** 2018-05-26 19:43 UTC
